name = "glint-analytics-pump"
main = "glint-analytics-pump.ts"
compatibility_date = "2024-01-01"

# Cron trigger - runs every 10 minutes to populate analytics
# Format: minute hour day month weekday
# Every 10 minutes: "*/10 * * * *"
# Other options: "*/5 * * * *" (every 5 min), "0 * * * *" (every hour)
[triggers]
crons = ["*/10 * * * *"]

# Environment variables (set via wrangler secret put)
# You can set either:
#   - GLINT_API_URL: Full API URL (e.g., https://glint-dun.vercel.app/api/trackAnalytics)
#   - LIVE_SITE: Base URL (e.g., https://glint-dun.vercel.app) - will append /api/trackAnalytics
#
# To set secrets:
#   wrangler secret put LIVE_SITE
#   or
#   wrangler secret put GLINT_API_URL
#
# Or set in Cloudflare Dashboard > Workers & Pages > glint-analytics-pump > Settings > Variables

[vars]
# Local development only - use secrets for production
# LIVE_SITE = "https://glint-dun.vercel.app"

